language: php

matrix:
  include:
    - php: 7.1
      env: deps=low
    - php: hhvm
      env: deps=low
    - php: hhvm
    - php: 7.1

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer self-update -q
  - if [ "$deps" = "no" ]; then composer --prefer-stable --prefer-dist -n update; fi;
  - if [ "$deps" = "low" ]; then composer --prefer-lowest -n --prefer-stable --prefer-dist update; fi;

script:
  - vendor/bin/phpmd src/ text cleancode, codesize, controversial, design, naming, unusedcode
  - vendor/bin/phpunit
